PcmtCISBundle\Entity\Subscription:
    constraints:
        - PcmtCISBundle\Constraint\RequiredFieldConstraint: ~

    properties:
        dataRecipientsGLN:
            - NotBlank: ~
        dataSourcesGLN:
            - NotBlank: ~
