parameters:
    pcmt_catalog.attribute_type.concatenated.class: PcmtProductBundle\Extension\ConcatenatedAttribute\Structure\Component\AttributeType\ConcatenatedAttributeType

services:
    pcmt_catalog.attributetype.concatenated:
        class: '%pcmt_catalog.attribute_type.concatenated.class%'
        tags:
          - { name: pim_catalog.attribute_type, alias: pcmt_catalog_concatenated, entity: '%pim_catalog.entity.product.class%' }

