services:

    PcmtProductBundle\Command\Handler\PcmtReferenceDataDownloadHandler:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:handler:download_reference_data' }

    PcmtProductBundle\Command\Handler\PcmtReferenceDataImportHandler:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:handler:import_reference_data' }