services:

    pcmt_catalog.job.job_parameters.default_values_provider.compute_family_products_concatenated_attributes_values:
        class: '%akeneo_batch.job.job_parameters.empty_values_provider.class%'
        arguments:
            - [ '%pcmt_catalog.compute_family_products_concatenated_attributes_values.job_name%' ]
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pcmt_connector.job.job_parameters.default_values_provider.reference_data_download_xmls:
        class: PcmtProductBundle\JobParameters\DefaultValueProvider\XmlReferenceDataDownload
        arguments:
            -
                - 'reference_data_download_xmls'
            - 'gs1Codes'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }


    pcmt_connector.job.job_parameters.default_values_provider.reference_data_import_xmls:
        class: PcmtProductBundle\JobParameters\DefaultValueProvider\XmlReferenceDataImport
        arguments:
            -
                - 'reference_data_import_xml'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }