parameters:
    pcmt_catalog.job.job_parameters.constraint_collection_provider.compute_family_products_concatenated_attributes_values.class: PcmtProductBundle\Connector\Job\JobParameters\ConstraintCollectionProvider\ComputeConcatenatedAttributeValuesOfProducts

services:
    pcmt_catalog.job.job_parameters.constraint_collection_provider.compute_family_products_concatenated_attributes_values:
        class: '%pcmt_catalog.job.job_parameters.constraint_collection_provider.compute_family_products_concatenated_attributes_values.class%'
        arguments:
            - ['compute_concatenated_attributes_values']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    pcmt_connector.job.job_parameters.constraint_collection_provider.reference_data_download_xmls:
        class: PcmtProductBundle\JobParameters\ConstraintCollectionProvider\XmlReferenceDataDownload
        arguments:
            -
                - 'reference_data_download_xmls'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    pcmt_connector.job.job_parameters.constraint_collection_provider.reference_data_import_xmls:
        class: PcmtProductBundle\JobParameters\ConstraintCollectionProvider\XmlReferenceDataImport
        arguments:
            -
                - 'reference_data_import_xml'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }