services:

    pcmt_catalog.repository.family_variant:
        class: PcmtProductBundle\Repository\PcmtFamilyVariantRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.family_variant.class%']
        tags:
            - { name: 'pim_repository' }