config:
    paths:
        dnd/product-edit-form/attributes/description: pcmtproduct/js/product/form/attributes/description

        ### Dashboard widget
        pcmt/product/widget/draft-products-widget: pcmtproduct/js/draft/draft-products-widget
        pcmt/product/draft/list: pcmtproduct/js/draft/draft_list

        ### form ###
        pcmt/product/draft/form/save: pcmtproduct/js/draft/form/save
        pcmt/product/draft/form/variant-navigation: pcmtproduct/js/draft/form/variant-navigation
        pcmt/product/draft/form/cache-invalidator: pcmtproduct/js/draft/form/cache-invalidator
        pcmt/product/draft/form/sequential-edit: pcmtproduct/js/draft/form/sequential-edit
        pcmt/product/draft/form/product-label: pcmtproduct/js/draft/form/product-label
        pcmt/product/draft/form/product-completeness: pcmtproduct/js/draft/form/product-completeness
        pcmt/product/draft/form/total-missing-required-attributes: pcmtproduct/js/draft/form/total-missing-required-attributes
        pcmt/product/draft/form/history: pcmtproduct/js/draft/form/history
        pcmt/product/draft/form/comments: pcmtproduct/js/draft/form/comments
        pcmt/product/draft/form/associations: pcmtproduct/js/draft/form/associations
        pcmt/product/draft/form/categories: pcmtproduct/js/draft/form/categories
        pcmt/product/draft/form/completeness: pcmtproduct/js/draft/form/completeness
        pcmt/product/draft/form/attribute-filter-at-this-level: pcmtproduct/js/draft/form/attribute-filter-at-this-level
        pcmt/product/draft/form/attributes/completeness: pcmtproduct/js/draft/form/attributes/completeness
        pcmt/product/draft/form/attributes/variant-axes: pcmtproduct/js/draft/form/attributes/variant-axes
        pcmt/product/draft/form/attributes/read-only-parent-attributes: pcmtproduct/js/draft/form/attributes/read-only-parent-attributes
        pcmt/product/draft/form/attributes/attribute-group-selector: pcmtproduct/js/draft/form/attributes/attribute-group-selector
        pcmt/product/draft/form/meta/updated: pcmtproduct/js/draft/form/meta/updated
        pcmt/product/draft/form/meta/created: pcmtproduct/js/draft/form/meta/created
        pcmt/product/draft/form/meta/family: pcmtproduct/js/draft/form/meta/family
        pcmt/product/draft/form/meta/family-variant: pcmtproduct/js/draft/form/meta/family-variant
        pcmt/product/draft/form/meta/change-family: pcmtproduct/js/draft/form/meta/change-family

        ### common ###
        pcmt/draft/common/breadcrumbs: pcmtproduct/js/draft/common/breadcrumbs
        pcmt/draft/common/attributes: pcmtproduct/js/draft/common/attributes
        pcmt/draft/common/main-image: pcmtproduct/js/draft/common/main-image
        pcmt/draft/common/updated: pcmtproduct/js/draft/common/updated
        pcmt/draft/common/created: pcmtproduct/js/draft/common/created

        ### templates ###
        pcmt/product/template/widget/draft-products-widget: pcmtproduct/templates/draft/draft-products-widget.html
        pcmt/product/template/widget/view-all-btn: pcmtproduct/templates/draft/view-all-btn.html
        pcmt/product/template/draft-list: pcmtproduct/templates/draft/draft-list.html

        ### controllers ###
        pcmt/product/drafts/index: pcmtproduct/js/controller/drafts_index
        pcmt/product/drafts/edit: pcmtproduct/js/controller/drafts_edit

        ### fetchers ###
        pcmt/draft-fetcher: pcmtproduct/js/draft/fetcher/draft_fetcher

        dnd/attribute-edit-form/descriptions/translation: pcmtproduct/js/attribute/form/descriptions/translation
        dnd/template/form/properties/translation: pcmtproduct/templates/form/properties/translation.html
        dnd/controller/attribute/create: pcmtproduct/js/controller/attribute/create

        pim/attribute-form-properties/concat-attribute-create: pcmtproduct/js/attribute/form/properties/concat-attribute
        pim/template/form/properties/concat-attribute: pcmtproduct/templates/form/properties/concat-attribute.html

        #concat attribute select dropdown - module
        pcmt/attribute-edit-form-properties/concat-attribute-select: pcmtproduct/js/attribute/form/properties/concat-attribute-select-attribute

        #concat attribute display value field
        pcmt/concatenated: pcmtproduct/js/attribute/field/concat-attribute-text-field

        pcmt_connector_button: pcmtproduct/js/common/button

    config:
        pim/controller-registry:
            controllers:
                pcmt_product_drafts_index:
                    module: pcmt/product/drafts/index
                pcmt_product_drafts_edit:
                    module: pcmt/product/drafts/edit
                    config:
                        entity: draft
                pim_enrich_attribute_create:
                    module: dnd/controller/attribute/create
            defaultController:
                module: pim/controller/template

        pim/fetcher-registry:
            fetchers:
                default: pim/base-fetcher
                concat-attribute:
                    module: pim/attribute-fetcher
                    options:
                        identifier_type: pim_catalog_identifier
                        urls:
                            list: pim_enrich_attribute_rest_index
                            get: pim_enrich_attribute_rest_get
                draft:
                    module: pcmt/draft-fetcher
                    options:
                        urls:
                            get: pcmt_product_drafts_api
        pcmt/template/form/poperties/concat-attribute:
            fieldName: concatenated

        pim/form/common/attributes/create-button:
            attribute_icons:
                pcmt_catalog_concatenated: file

        pim/attribute-edit-form/type-specific-form-registry:  #configuration for concatenated attribute type create/edit form
            formNames:
                pcmt_catalog_concatenated:
                    create: pcmt-attribute-form-concatenated
                    edit: pcmt-attribute-form-concatenated

