parameters:
    pcmt_catalog.job.job_parameters.constraint_collection_provider.compute_family_products_concatenated_attributes_values.class: Pcmt\PcmtFamilyBundle\Connector\Job\JobParameters\ConstraintCollectionProvider\ComputeConcatenatedAttributeValuesOfProducts

services:
    pcmt_catalog.job.job_parameters.constraint_collection_provider.compute_family_products_concatenated_attributes_values:
        class: '%pcmt_catalog.job.job_parameters.constraint_collection_provider.compute_family_products_concatenated_attributes_values.class%'
        arguments:
            - ['compute_concatenated_attributes_values']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }