parameters:
    pcmt_catalog.tasklet.compute_family_products_concatenated_attributes_values.class: Pcmt\PcmtFamilyBundle\Connector\Job\ComputeConcatenatedAttributeValuesOfProductsTasklet

    pcmt_catalog.compute_family_products_concatenated_attributes_values.tasklet_name: 'compute_concatenated_attributes_values'
    pcmt_catalog.compute_family_products_concatenated_attributes_values.job_name: 'compute_concatenated_attributes_values'
    pcmt_catalog.compute_family_products_concatenated_attributes_values.job_type: 'compute_concatenated_attributes_values'
    pcmt_catalog.compute_family_products_concatenated_attributes_values.connector_name: 'compute_concatenated_attributes_values'

services:

    pcmt_catalog.tasklet.compute_family_products_concatenated_attributes_values:
        class: '%pcmt_catalog.tasklet.compute_family_products_concatenated_attributes_values.class%'
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pcmt_catalog.product.updater.concatenated_attributes_for_product_and_model'
            - '@pim_catalog.saver.product'
            - '@pim_catalog.saver.product_model'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.family'
            - '@pim_catalog.repository.family_variant'
            - '@pim_catalog.repository.product_model'
            - '@pim_connector.doctrine.cache_clearer'
            - '%pcmt_catalog.compute_family_products_concatenated_attributes_values.job_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
        public: false

    pcmt_catalog.step.compute_family_products_concatenated_attributes_values:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - '%pcmt_catalog.compute_family_products_concatenated_attributes_values.tasklet_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pcmt_catalog.tasklet.compute_family_products_concatenated_attributes_values'
        public: false

    pcmt_catalog.job.compute_family_products_concatenated_attributes_values:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pcmt_catalog.compute_family_products_concatenated_attributes_values.job_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pcmt_catalog.step.compute_family_products_concatenated_attributes_values'
        public: false
        tags:
            -
                name: akeneo_batch.job
                connector: '%pcmt_catalog.compute_family_products_concatenated_attributes_values.connector_name%'
                type: '%pcmt_catalog.compute_family_products_concatenated_attributes_values.job_type%'
            -
                name: akeneo_batch.job.not_visible