---
- hosts: docker-hosts
  gather_facts: false
  become: yes
  pre_tasks:
    - include_tasks: tasks/python2-ubuntu.yml
    - setup:
  roles:
    - role: geerlingguy.docker
  tasks:
    - include_tasks: tasks/pim.yml
    