---
- hosts: docker-hosts
  gather_facts: True
  become: yes
  pre_tasks:
    - include_tasks: tasks/python2-ubuntu.yml
    - setup:
  #vars:
  #  pip_install_packages:
  #      - name: docker
  roles:
   # - role: geerlingguy.pip
    - role: geerlingguy.docker