######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

############### Beta Environment ###############

.env-beta:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: beta
    url: http://beta.pcmt.villagereach.org
    on_stop: env-beta-destroy

.env-beta_script-deploy:
  script:
    - ./bin/ci-deploy.sh beta
    
.env-beta_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh beta destroy -auto-approve

env-beta (WIPE DB):
  extends:
    - .env-beta
    - .env-beta_script-deploy
  variables:
    PCMT_PROFILE: dev

env-beta (KEEP DB):
  extends:
    - .env-beta
    - .env-beta_script-deploy
  variables:
    PCMT_PROFILE: production

env-beta-destroy:
  extends:
    - .env-beta
    - .env-beta_script-destroy
  environment:
    name: beta
    action: stop

############### Rwanda Beta Environment ###############

.env-rwanda-beta:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: rwanda-beta
    url: http://rwanda-beta.pcmt.villagereach.org
    on_stop: env-rwanda-beta-destroy

.env-rwanda-beta_script-deploy:
  script:
    - ./bin/ci-deploy.sh rwanda-beta
    
.env-rwanda-beta_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh rwanda-beta destroy -auto-approve

env-rwanda-beta (WIPE DB):
  extends:
    - .env-rwanda-beta
    - .env-rwanda-beta_script-deploy
  variables:
    PCMT_PROFILE: dev

env-rwanda-beta (KEEP DB):
  extends:
    - .env-rwanda-beta
    - .env-rwanda-beta_script-deploy
  variables:
    PCMT_PROFILE: production

env-rwanda-beta-destroy:
  extends:
    - .env-rwanda-beta
    - .env-rwanda-beta_script-destroy
  environment:
    name: rwanda-beta
    action: stop

############### Ethiopia Beta Environment ###############

.env-ethiopia-beta:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: ethiopia-beta
    url: http://ethiopia-beta.pcmt.villagereach.org
    on_stop: env-ethiopia-beta-destroy

.env-ethiopia-beta_script-deploy:
  script:
    - ./bin/ci-deploy.sh ethiopia-beta
    
.env-ethiopia-beta_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh ethiopia-beta destroy -auto-approve

env-ethiopia-beta (WIPE DB):
  extends:
    - .env-ethiopia-beta
    - .env-ethiopia-beta_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: 1.0.0-beta2

env-ethiopia-beta (KEEP DB):
  extends:
    - .env-ethiopia-beta
    - .env-ethiopia-beta_script-deploy
  variables:
    PCMT_PROFILE: production

env-ethiopia-beta-destroy:
  extends:
    - .env-ethiopia-beta
    - .env-ethiopia-beta_script-destroy
  environment:
    name: ethiopia-beta
    action: stop

############### Ethiopia Demo Environment ###############

.env-ethiopia-demo:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: ethiopia-demo
    url: http://ethiopia-demo.productcatalog.io
    on_stop: env-ethiopia-demo-destroy

.env-ethiopia-demo_script-deploy:
  script:
    - ./bin/ci-deploy.sh ethiopia-demo
    
.env-ethiopia-demo_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh ethiopia-demo destroy -auto-approve

env-ethiopia-demo (WIPE DB):
  extends:
    - .env-ethiopia-demo
    - .env-ethiopia-demo_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: '1.0.0'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.0.0/pcmt-v1.0.0.tar.gz'

env-ethiopia-demo (KEEP DB):
  extends:
    - .env-ethiopia-demo
    - .env-ethiopia-demo_script-deploy
  variables:
    PCMT_PROFILE: production
    PCMT_VER: 1.0.0
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.0.0/pcmt-v1.0.0.tar.gz'

env-ethiopia-demo-destroy:
  extends:
    - .env-ethiopia-demo
    - .env-ethiopia-demo_script-destroy
  environment:
    name: ethiopia-demo
    action: stop

############### Rwanda Demo Environment ###############

.env-rwanda-demo:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: rwanda-demo
    url: http://rwanda-demo.productcatalog.io
    on_stop: env-rwanda-demo-destroy

.env-rwanda-demo_script-deploy:
  script:
    - ./bin/ci-deploy.sh rwanda-demo
    
.env-rwanda-demo_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh rwanda-demo destroy -auto-approve

env-rwanda-demo (WIPE DB):
  extends:
    - .env-rwanda-demo
    - .env-rwanda-demo_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: '1.0.0'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.0.0/pcmt-v1.0.0.tar.gz'

env-rwanda-demo (KEEP DB):
  extends:
    - .env-rwanda-demo
    - .env-rwanda-demo_script-deploy
  variables:
    PCMT_PROFILE: production
    PCMT_VER: 1.0.0
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.0.0/pcmt-v1.0.0.tar.gz'

env-rwanda-demo-destroy:
  extends:
    - .env-rwanda-demo
    - .env-rwanda-demo_script-destroy
  environment:
    name: rwanda-demo
    action: stop

############### Demo Environment ###############

.env-demo:
  extends:
    - .pim_only_changes
  stage: deploy
  only:
    - master@pcmt/pcmt
  when: manual
  environment:
    name: demo
    url: http://demo.productcatalog.io
    on_stop: env-demo-destroy

.env-demo_script-deploy:
  script:
    - ./bin/ci-deploy.sh demo
    
.env-demo_script-destroy:
  script: 
    - ./deploy/terraform/run-docker.sh demo destroy -auto-approve

env-demo (WIPE DB):
  extends:
    - .env-demo
    - .env-demo_script-deploy
  variables:
    PCMT_PROFILE: dev
    PCMT_VER: '1.0.0'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.0.0/pcmt-v1.0.0.tar.gz'

env-demo (KEEP DB):
  extends:
    - .env-demo
    - .env-demo_script-deploy
  variables:
    PCMT_PROFILE: production
    PCMT_VER: 1.0.0
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt/-/archive/v1.0.0/pcmt-v1.0.0.tar.gz'

env-demo-scheduled-reset:
  extends:
    - 'env-demo (WIPE DB)'
  only:
    refs:
      - schedules
    variables:
      - $CI_JOB_NAME == "env-demo-scheduled-reset"
  
env-demo-destroy:
  extends:
    - .env-demo
    - .env-demo_script-destroy
  environment:
    name: demo
    action: stop