######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: "3.0"
services: 
  fpm:
    volumes:
      - 'pim:/srv/pim'
      - './pim/src:/srv/pim/src:rw'
      - './pim/app:/tmp/pcmt/app:ro'
      - './pim/web:/tmp/pcmt/web:ro'
      - './pim/composer.json:/srv/pim/composer.json'
      - './pim/composer.lock:/srv/pim/composer.lock'
      - './pim/ecs.yml:/srv/pim/ecs.yml'
    # we use depends_on so that the pim volume is initialized by one container
    # with a complete /srv/pim.  Otherwise there isn't a gurantee how this
    # volume will be initialized.
    depends_on: 
      - httpd
    environment: # comments below left intentionally - xdebug testing
      - PHP_XDEBUG_ENABLED=1
     # - PHP_XDEBUG_REMOTE_HOST=172.18.0.1
     # - PHP_XDEBUG_REMOTE_HOST=172.20.0.1  #tcpdump shows tcp activity on this host and port.
     # - PHP_XDEBUG_REMOTE_HOST=10.222.17.199  #tcpdump shows no tcp activity on this host:port
      - PHP_XDEBUG_REMOTE_PORT=9000

  elasticsearch:
    ports:
      - '9200:9200'

  node:
    image: 'node:10-slim'
    user: 'node'
    volumes:
      - 'pim:/srv/pim'
      - './pim/src:/srv/pim/src:ro'
    working_dir: '/srv/pim'
    networks:
     - akeneo

  mysql:
    ports:
      - '3306:3306'

  httpd:
    volumes:
      - 'pim:/srv/pim'

volumes:
  pim:
    driver: local