######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: "3.0"
services: 
  fpm:
    volumes:
      - 'pim:/srv/pim'
      - './pim/src:/srv/pim/src:ro'
      - './pim/app:/tmp/pcmt/app:ro'
      - './pim/composer.json:/srv/pim/composer.json'
      - './pim/composer.lock:/srv/pim/composer.lock'
    # we use depends_up so that the pim volume is initialized by one container 
    # with a complete /srv/pim.  Otherwise there isn't a gurantee how this
    # volume will be initialized.
    depends_on: 
      - httpd
  
  node:
    image: 'node:10-slim'
    user: 'node'
    volumes:
      - 'pim:/srv/pim'
      - './pim/src:/srv/pim/src:ro'
    working_dir: '/srv/pim'
    networks:
     - akeneo

  httpd:
    volumes:
      - 'pim:/srv/pim'

volumes:
  pim:
    driver: local