######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: "3.0"
services: 
  fpm:
    volumes:
      - "pim:/srv/pim"
      - "./pim/src:/srv/pim/src:ro"
      - "./pim/app:/tmp/pcmt/app:ro"
      - "./pim/composer.json:/srv/pim/composer.json:ro"
      - "./pim/composer.lock:/srv/pim/composer.lock:rw"
    entrypoint: ["/srv/pim/start.sh"]
    depends_on:
      - mysql
      - elasticsearch
      - node
      - httpd
  
  node:
    image: 'node:10-slim'
    user: 'node'
    volumes:
      - 'pim:/srv/pim'
    working_dir: '/srv/pim'
    networks:
     - akeneo

  httpd:
    volumes:
      - "pim:/srv/pim"

volumes:
  pim:
    driver: local