######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: "3.5"
services:
  fpm:
    volumes:
      - 'pim:/srv/pim'
      - './pim/src:/srv/pim/src:rw'
      - './pim/app:/tmp/pcmt/app:ro'
      - './pim/web:/tmp/pcmt/web:ro'
      - './pim/composer.json:/srv/pim/composer.json'
      - './pim/composer.lock:/srv/pim/composer.lock'
      - './pim/crontab:/srv/pim/crontab'
      - './pim/ecs.yml:/srv/pim/ecs.yml'
      - './pim/phpunit.xml.dist:/srv/pim/phpunit.xml.dist:ro'
      - './pim/crontab:/srv/pim/crontab'
      - './build/phpstorm-coverage:/opt/phpstorm-coverage'
    # we use depends_on so that the pim volume is initialized by one container
    # with a complete /srv/pim.  Otherwise there isn't a gurantee how this
    # volume will be initialized.
    depends_on:
      - httpd
    environment:
      - PHP_XDEBUG_ENABLED=1
      - PHP_XDEBUG_REMOTE_PORT=9000

  elasticsearch:
    ports:
      - '9200:9200'

  node:
    image: 'node:10-slim'
    user: 'node'
    volumes:
      - 'pim:/srv/pim'
      - './pim/src:/srv/pim/src:ro'
    working_dir: '/srv/pim'
    networks:
     - akeneo

  mysql:
    ports:
      - '3306:3306'

  httpd:
    volumes:
      - 'pim:/srv/pim'

volumes:
  pim:
    driver: local