version: "3.5"
services:
    fpm:
        volumes:
            - 'ftp-get:/srv/pim/src/PcmtCoreBundle/Resources/E2OpenImport/work/'
    
    mysql-backup:
        image: pcmt/mysql-backup
        environment:
            CRON_SCHEDULE: '*/15 * * * *'
            BACKUP_DIR: '/backup'
        secrets:
            - mysql-creds
        volumes:
            - mysql-backup:/backup
        networks:
            - 'akeneo'

    s3-sync:
        image: pcmt/s3
        environment:
            CRON_SCHEDULE: '1,31 * * * *'
            LOCAL_DIR_TO_SYNC_OUT: '/backup'
            S3_BUCKET: "${PCMT_S3_BUCKET:-$PCMT_HOSTNAME}"
        volumes:
            - mysql-backup:/backup
        secrets:
            - s3-creds

    ftp-get:
        image: pcmt/ftp-get
        environment:
            CRON_SCHEDULE: '*/10 * * * *'
            SFTP_PRIVKEY_FILENAME: '/run/secrets/sftp-privkey'
            SFTP_LOCAL_DIR: '/srv/pim/src/PcmtCoreBundle/Resources/E2OpenImport/work/'
        volumes:
            - 'ftp-get:/srv/pim/src/PcmtCoreBundle/Resources/E2OpenImport/work/'
        secrets:
            - ftp-get-creds
            - sftp-privkey
            
volumes:
    mysql-backup:
        driver: local
    ftp-get:
        driver: local

secrets:
    mysql-creds:
        file: "${PCMT_MYSQL_CREDS_CONF:-./conf/mysql-creds.env}"
    s3-creds:
        file: "${PCMT_S3_CREDS_CONF:-./conf/aws-s3-creds.env}"
    ftp-get-creds:
        file: "${PCMT_FTP_GET_CREDS_CONF:-./conf/ftp-get-creds.env}"
    sftp-privkey:
        file: ${PCMT_SFTP_PRIVKEY_FILENAME:-./conf/sftp-privkey}
        