version: "3.5"
services:
    mysql-backup:
        image: pcmt/mysql-backup
        environment:
            CRON_SCHEDULE: '*/2 * * * *'
            BACKUP_DIR: '/backup'
        secrets:
            - mysql-creds
        volumes:
            - mysql-backup:/backup
        networks:
            - 'akeneo'

    s3-sync:
        image: pcmt/s3
        environment:
            CRON_SCHEDULE: '1-59/2 * * * *'
            LOCAL_DIR_TO_SYNC_OUT: '/backup'
        volumes:
            - mysql-backup:/backup
        secrets:
            - s3-creds

    ftp-get:
        image: pcmt/ftp-get
        environment:
            CRON_SCHEDULE: '*/10 * * * *'
            SFTP_PRIVKEY_FILENAME: '/run/secrets/sftp-privkey'
        volumes:
            - ftp-get:/downloads
        secrets:
            - ftp-get-creds
            - sftp-privkey
            
volumes:
    mysql-backup:
        driver: local

secrets:
    mysql-creds:
        file: "${PCMT_MYSQL_CREDS_CONF:-./conf/mysql-creds.env}"
    s3-creds:
        file: "${PCMT_S3_CREDS_CONF:-./conf/aws-s3-creds.env}"
    ftp-get-creds:
        file: "${PCMT_FTP_GET_CREDS_CONF:-./conf/ftp-get-creds.env}"
    sftp-privkey:
        file: ${PCMT_SFTP_PRIVKEY_FILENAME:-./conf/sftp-privkey}
        