---
- name: Create app and conf directories
  file:
    path: /app/conf
    state: directory
    mode: 0744 
- name: Get PCMT docker-compose file
  get_url: 
    url:  "{{ pcmt_asset_url }}/docker-compose.yml"
    dest: /app/
- name: Get PCMT .env file
  get_url: 
    url:  "{{ pcmt_asset_url }}/.env"
    dest: /app/
- name: Get PCMT settings.env file
  get_url: 
    url:  "{{ pcmt_asset_url }}/settings.env"
    dest: /app/
- name: Get PCMT parameters.yml file
  get_url: 
    url:  "{{ pcmt_asset_url }}/conf/parameters.yml.dist"
    dest: /app/conf/parameters.yml
- name: Pull and Start PCMT images
  vars:
    pcmt_profile: "{{ lookup('env', 'PCMT_PROFILE') }}"
    pcmt_ver: "{{ lookup('env', 'PCMT_VER') }}"
  environment:
    PCMT_PROFILE: "{{ pcmt_profile }}"
    PCMT_VER: "{{ pcmt_ver }}"
    PCMT_SECRET_CONF: "conf/parameters.yml"
  docker_service:
    project_src: /app
    build: no
    pull: yes
    restarted: yes
    state: present
- name: Prune docker system
  shell: docker system prune -af