---
- name: Clear app directory
  file:
    path: /app/
    state: absent
- name: Create app directory
  file:
    path: /app/
    state: directory
    mode: 0744 
- name: Get PCMT asset archive
  get_url:
    url: "{{ pcmt_asset_url }}"
    dest: /app/pcmt.tar.gz
- name: Unarchive pcmt
  unarchive:
    src: /app/pcmt.tar.gz
    dest: /app/
    remote_src: yes
    extra_opts:
      - --strip-components=1
- name: Pull and Start PCMT images
  vars:
    pcmt_profile: "{{ lookup('env', 'PCMT_PROFILE') }}"
    pcmt_ver: "{{ lookup('env', 'PCMT_VER') }}"
  environment:
    PCMT_PROFILE: "{{ pcmt_profile }}"
    PCMT_VER: "{{ pcmt_ver }}"
    PCMT_SECRET_CONF: "./conf/parameters.yml.dist"
    PCMT_TRAEFIK_CONF: "./conf/traefik.toml.dist"
  docker_service:
    project_src: /app
    build: no
    pull: yes
    remove_orphans: yes
    restarted: yes
    state: present
- name: Prune docker system
  shell: docker system prune -af