---
- name: Create app directory
  file:
    path: /app
    state: directory
    mode: 0744 
- name: Get PCMT docker-compose file
  get_url: 
    url:  https://gitlab.com/pcmt/pcmt/raw/master/docker-compose.yml
    dest: /app/
- name: Get PCMT .env file
  get_url: 
    url:  https://gitlab.com/pcmt/pcmt/raw/master/.env
    dest: /app/
- name: Get PCMT settings.env file
  get_url: 
    url:  https://gitlab.com/pcmt/pcmt/raw/master/settings.env
    dest: /app/
- name: Pull and Start PCMT images
  docker_service:
    project_src: /app
    build: no
    pull: yes
    restarted: yes
    state: present