extensions:
    pcmt-menu-gs1-codes:                          # The unique key of your extension
        module: pim/menu/item                           # The module provided by akeneo for root elements
        parent: pim-menu-reference_data-navigation-block             # The parent is the root of the menu
        position: 10
        config:
            title: GS1 codes
            #to: pim_importexport_import_profile_index
            to: pim_customentity_index
            routeParams:
                customEntityName: GS1Code