services:

  Pcmt\Bundle\PcmtConnectorBundle\Command\Handler\PcmtReferenceDataDownloadHandler:
    autowire: true
    tags:
      - { name: 'console.command', command: 'pcmt:handler:download_reference_data' }

  Pcmt\Bundle\PcmtConnectorBundle\Command\Handler\PcmtReferenceDataImportHandler:
    autowire: true
    tags:
      - { name: 'console.command', command: 'pcmt:handler:import_reference_data' }