services:

  pcmt_connector.job.job_parameters.default_values_provider.reference_data_download_xmls:
    class: Pcmt\Bundle\PcmtConnectorBundle\JobParameters\DefaultValueProvider\XmlReferenceDataDownload
    arguments:
      -
        - 'reference_data_download_xmls'
      - 'gs1Codes'
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }


  pcmt_connector.job.job_parameters.default_values_provider.reference_data_import_xmls:
    class: Pcmt\Bundle\PcmtConnectorBundle\JobParameters\DefaultValueProvider\XmlReferenceDataImport
    arguments:
      -
        - 'reference_data_import_xml'
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }