parameters:

  pcmt_connector.name: 'Pcmt Connector'

services:

####### JOBS ###########

  pcmt_connector.job.reference_data_download_xmls:
    class: '%pim_connector.job.simple_job.class%'
    arguments:
      - 'reference_data_download_xmls'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      -
        - '@pcmt_xml_connector.step.xml_reference_data_download'
    tags:
      - { name: akeneo_batch.job, connector: 'Pcmt Connector', type: 'download' }


  pcmt_connector.job.reference_data_import_xmls:
    class: '%pim_connector.job.simple_job.class%'
    arguments:
      - 'reference_data_import_xml'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      -
        - '@pcmt_xml_connector.step.xml_reference_data_import'

    tags:
      - { name: akeneo_batch.job, connector: 'Pcmt Connector', type: '%pim_connector.job.import_type%' }




