imports:
  - { resource: steps.yml }
  - { resource: jobs.yml }

services:

  Pcmt\Bundle\PcmtConnectorBundle\Command\InitializeReferenceDataImport:
    autowire: true
    tags:
      - { name: 'console.command', command: 'pcmt:reference_data:create' }