datagrid:
    rule-grid:
        options:
            entityHint: rule
            manageFilters: false
        source:
            type:              pcmt_datasource_rule
            entity:            '%pcmt.entity.rule.class%'
            user_config_alias: rule-grid
            acl_resource:      pcmt_permission_rules_view
        columns:
            id:
                label:     ID
                type:      field
            unique_id:
                label:     Label
                type:      field
            source_family:
                label: Source Family
                type: field
            destination_family:
                label: Destination Family
                type: field
            key_attribute:
                label: Key attribute
                type: field
        properties:
            id: ~
            edit_link:
                type: url
                route: pcmt_rules_edit
                params:
                    - id
            run_link:
                type: url
                route: pcmt_rule_rest_run
                params:
                    - id
        actions:
            edit:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:      navigate
                label:     pim_common.edit
                link:      edit_link
                rowAction: true
                acl_resource: pcmt_permission_rules_edit
            run:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--play
                type:         ajax
                label:        pcmt.rules.action.run.label
                link:         run_link
                acl_resource: pcmt_permission_rules_run

