######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    #### Drafts Fetcher for dashboard w/ user context ####
    pcmt_catalog.draft.fetcher:
        class: PcmtDraftBundle\Widget\DraftsFetcher
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@oro_security.security_facade'
