######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt_core.save.productDraft:
        class: PcmtDraftBundle\Saver\ProductDraftSaver
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'

    pcmt_core.save.productModelDraft:
        class: PcmtDraftBundle\Saver\ProductModelDraftSaver
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'