######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt.saver.draft:
        class: PcmtDraftBundle\Saver\DraftSaver
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@pcmt_catalog.repository.draft'

