######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt.service.builder.response_builder:
        class: PcmtCoreBundle\Service\Builder\ResponseBuilder
        arguments:
            - '@pim_internal_api_serializer'

    pcmt.manager.draft_facade:
        class: PcmtDraftBundle\Manager\DraftFacade
        autowire: true

    pcmt.service.product_draft_approver:
        class: PcmtDraftBundle\Service\Draft\ProductDraftApprover
        autowire: true
        calls:
            - [setValidator, ['@pim_catalog.validator.product']]
            - [setSaver, ['@pim_catalog.saver.product']]
            - [setCreator, ['@pcmt.service.product_from_draft_creator']]

    pcmt.service.product_model_draft_approver:
        class: PcmtDraftBundle\Service\Draft\ProductModelDraftApprover
        autowire: true
        calls:
            - [setValidator, ['@pim_catalog.validator.product']]
            - [setSaver, ['@pim_catalog.saver.product_model']]
            - [setCreator, ['@pcmt.service.product_model_from_draft_creator']]

    pcmt.service.product_from_draft_creator:
        class: PcmtDraftBundle\Service\Draft\ProductFromDraftCreator
        arguments:
            - '@pim_catalog.builder.product'
            - '@pim_enrich.converter.enrich_to_standard.product_value'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_user.context.user'
            - '@pim_catalog.comparator.filter.product'
            - '@pim_catalog.updater.product'
            - '@pim_enrich.filter.product_attribute_filter'

    pcmt.service.product_model_from_draft_creator:
        class: PcmtDraftBundle\Service\Draft\ProductModelFromDraftCreator
        arguments:
            - '@pim_catalog.factory.product_model'
            - '@pim_enrich.converter.enrich_to_standard.product_value'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_user.context.user'
            - '@pim_catalog.comparator.filter.product_model'
            - '@pim_catalog.updater.product_model'
            - '@pim_enrich.filter.product_model_attribute_filter'

    pcmt.service.product_model_attribute_change:
        class: PcmtDraftBundle\Service\AttributeChange\ProductModelAttributeChangeService
        arguments:
            - '@pim_versioning.serializer'
            - '@pim_catalog.repository.attribute'
        autowire: true

    pcmt.service.product_attribute_change:
        class: PcmtDraftBundle\Service\AttributeChange\ProductAttributeChangeService
        arguments:
            - '@pim_versioning.serializer'
            - '@pim_catalog.repository.attribute'
        autowire: true

    pcmt_draft_saver_factory:
        class: 'PcmtDraftBundle\Service\Draft\DraftSaverFactory'
        arguments:
            - '@pcmt_core.save.productDraft'
            - '@pcmt_core.save.productModelDraft'
        autowire: true