services:
    pcmt_connector.step.xlsx_product_draft.import:
        class: 'PcmtDraftBundle\Connector\Job\Step\PcmtImportViaDraftStep'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.file.xlsx_product'
            - '@pim_connector.processor.denormalization.product'
            - '@pcmt_connector.job.writer.database.product_draft'
            - '%pim_job_product_batch_size%'
        calls:
            - [setUserRepository, ['@pim_user.repository.user']]
