services:

    pcmt_core.controller.rest.reference:
        class: 'PcmtCoreBundle\Controller\ReferenceDataController'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_standard_format_serializer'
