######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:
    pcmt_core.controller.rest.draft:
        class: PcmtCoreBundle\Controller\PcmtDraftController
        autowire: true
        arguments:
            $constraintViolationNormalizer: '@pim_enrich.normalizer.product_violation'

    ### overrides product controller
    pim_enrich.controller.rest.product:
        class: PcmtCoreBundle\Controller\PcmtProductController
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.updater.product'
            - '@pim_catalog.saver.product'
            - '@pim_internal_api_serializer'
            - '@pim_catalog.validator.product'
            - '@pim_user.context.user'
            - '@pim_catalog.filter.chained'
            - '@pim_enrich.filter.product_edit_data'
            - '@pim_catalog.remover.product'
            - '@pim_catalog.builder.product'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_catalog.comparator.filter.product'
            - '@pim_enrich.converter.enrich_to_standard.product_value'
            - '@pim_enrich.normalizer.product_violation'
            - '@pim_catalog.builder.product'
            - '@pim_enrich.filter.product_attribute_filter'
            - '@akeneo_elasticsearch.client.product'
            - '@akeneo_elasticsearch.client.product_and_product_model'
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]
            - [setDraftSaver, ['@pcmt_core.save.productDraft']]
            - [setResponseBuilder, ['@pcmt.service.builder.response_builder']]

    ### overrides product model controller
    pim_enrich.controller.rest.product_model:
        class: PcmtCoreBundle\Controller\PcmtProductModelController
        arguments:
            - '@pim_catalog.repository.product_model'
            - '@pim_internal_api_serializer'
            - '@pim_user.context.user'
            - '@pim_catalog.filter.chained'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_catalog.comparator.filter.product_model'
            - '@pim_enrich.converter.enrich_to_standard.product_value'
            - '@pim_catalog.updater.product_model'
            - '@pim_catalog.remover.product_model'
            - '@pim_catalog.validator.product'
            - '@pim_catalog.saver.product_model'
            - '@pim_enrich.normalizer.product_violation'
            - '@pim_enrich.normalizer.entity_with_family_variant'
            - '@pim_catalog.factory.product_model'
            - '@pim_enrich.normalizer.violation'
            - '@pim_catalog.repository.family_variant'
            - '@pim_enrich.filter.product_model_attribute_filter'
            - '@akeneo_elasticsearch.client.product_model'
            - '@akeneo_elasticsearch.client.product_and_product_model'
        calls:
            - [setDraftSaver, ['@pcmt_core.save.productModelDraft']]
            - [setResponseBuilder, ['@pcmt.service.builder.response_builder']]
