services:

    #### Drafts Fetcher for dashboard w/ user context ####
    pcmt_catalog.draft.fetcher:
        class: PcmtCoreBundle\Widget\DraftsFetcher
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@oro_security.security_facade'
