######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:


    ### Concatenated fields for attribute
    pcmt_catalog.normalizer.standard.concatenated_attribute:
        class: 'PcmtCoreBundle\Normalizer\Standard\ConcatenatedTypeNormalizer'
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }

    ### Attribute
    pim_catalog.normalizer.standard.attribute:
        class: 'PcmtCoreBundle\Normalizer\Standard\AttributeNormalizer'
        arguments:
            - '@pcmt_catalog.normalizer.standard.concatenated_attribute'
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.normalizer.standard.datetime'
            - ['auto_option_sorting']
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }

parameters:
    pim_catalog.normalizer.standard.translation.class: PcmtCoreBundle\Normalizer\Standard\TranslationNormalizer




