services:
    pcmt_catalog.draft_new.property_normalizer:
        class: PcmtCoreBundle\Normalizer\NewDraftPropertyNormalizer
        autowire: true
    pcmt_catalog.draft_pending.property_normalizer:
        class: PcmtCoreBundle\Normalizer\PendingDraftPropertyNormalizer
    pcmt_core.draft.status.normalizer:
        class: PcmtCoreBundle\Normalizer\DraftStatusNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 80 }
    pcmt_core.draft.attribute_change.normalizer:
        class: PcmtCoreBundle\Normalizer\AttributeChangeNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 120 }
    pcmt_core.draft.product_normalizer:
        class: PcmtCoreBundle\Normalizer\ProductDraftNormalizer
        autowire: true
        calls:
            - [setProductFromDraftCreator, ['@pcmt.service.product_from_draft_creator']]
            - [setProductAttributeChangeService, ['@pcmt.service.product_attribute_change']]
        arguments:
            $productNormalizer: '@pcmt_core.normalizer.product'
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 110 }
    pcmt_core.draft.product_model_normalizer:
        class: PcmtCoreBundle\Normalizer\ProductModelDraftNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 110 }
        calls:
            - [setProductModelFromDraftCreator, ['@pcmt.service.product_model_from_draft_creator']]
            - [setProductModelAttributeChangeService, ['@pcmt.service.product_model_attribute_change']]
    pcmt_core.normalizer.product:
        class: Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\ProductNormalizer
        arguments:
            - '@pim_standard_format_serializer'
            - '@pim_enrich.normalizer.version'
            - '@pim_versioning.manager.version'
            - '@pim_enrich.normalizer.image'
            - '@pim_catalog.repository.locale'
            - '@pim_structure_version.provider.structure_version.product'
            - '@pcmt.provider.form.draft'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_enrich.converter.standard_to_enrich.product_value'
            - '@pim_catalog.object_manager.product'
            - '@pim_catalog.manager.completeness'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.filter.chained'
            - '@pim_enrich.normalizer.completeness_collection'
            - '@pim_user.context.user'
            - '@pim_catalog.completeness.calculator'
            - '@pim_catalog.values_filler.product'
            - '@pim_catalog.family_variant.provider.entity_with_family_variant_attributes'
            - '@pim_enrich.normalizer.variant_navigation'
            - '@pim_enrich.doctrine.query.ascendant_categories'
            - '@pim_enrich.normalizer.incomplete_values'
            - '@pim_catalog.association.missing_association_adder'
            - '@pim_catalog.normalizer.standard.product.parent_associations'
            - '@pim_catalog.context.catalog'
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 110 }

    ### Concatenated fields for attribute
    pcmt_catalog.normalizer.standard.concatenated_attribute:
        class: 'PcmtCoreBundle\Normalizer\Standard\ConcatenatedTypeNormalizer'
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }

    ### Attribute
    pim_catalog.normalizer.standard.attribute:
        class: 'PcmtCoreBundle\Normalizer\Standard\AttributeNormalizer'
        arguments:
            - '@pcmt_catalog.normalizer.standard.concatenated_attribute'
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.normalizer.standard.datetime'
            - ['auto_option_sorting']
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }

parameters:
    pim_catalog.normalizer.standard.translation.class: PcmtCoreBundle\Normalizer\Standard\TranslationNormalizer




