######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt_catalog.repository.family_variant:
        class: PcmtCoreBundle\Repository\PcmtFamilyVariantRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.family_variant.class%']
        tags:
            - { name: 'pim_repository' }

    pcmt_catalog.repository.e2open_attribute_mapping:
        class: PcmtCoreBundle\Repository\AttributeMappingRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        tags:
            - { name: 'pim_repository' }