######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

pim_dashboard_index:
  path: /dashboard
  defaults: { _controller: FrameworkBundle:Template:template, template: PcmtCoreBundle:Dashboard:index.html.twig }

pim_enrich_product_rest_create:
  path: /rest
  defaults: { _controller: pim_enrich.controller.rest.product:createAction }
  methods: [PUT]

pim_enrich_product_model_rest_create:
  path: /rest/create
  defaults: { _controller: pim_enrich.controller.rest.product_model:createAction }
  methods: [PUT]