######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    #util command for the one below (PcmtCreateAllAttributesCommand)
    PcmtCoreBundle\Command\PcmtCreateAttributeForRefDataCommand:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:generate-ref-data-attr' }

    #util command - generate default reference data simple select attributes
    PcmtCoreBundle\Command\PcmtCreateAllAttributesCommand:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:generate-ref-data-attr-all' }

    PcmtCoreBundle\Command\Creator\PcmtJobCreator:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:job-creator' }

    pcmt_update_attribute.concatenated_fields_values:
        class: PcmtCoreBundle\Service\ConcatenatedAttribute\ConcatenatedAttributeCreator
        arguments:
            - '@logger'

    pcmt_e2Open_mapping:
        class: PcmtCoreBundle\Connector\Mapping\E2OpenMapping
        autowire: true

    pcmt_e2Open_mapping_handler:
        class: PcmtCoreBundle\Service\E2Open\E2OpenMappingHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.repository.family'
            - '@pcmt_catalog.repository.e2open_attribute_mapping'
            -
    pcmt_e2Open_attributes_service:
        class: PcmtCoreBundle\Service\E2Open\E2OpenAttributesService
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.family'
            - '%akeneo_measure.measures_config%'

    PcmtCoreBundle\Command\ProcessE2OpenImport:
        arguments:
            - '%e2Open_import_files_directory%'
            - '@monolog.logger'
        tags:
            - { name: 'console.command', command: 'pcmt:e2Open:import_from_files' }

    pcmt_core.service.esquery.product:
        class: PcmtCoreBundle\Service\Query\ESQuery
        arguments:
            - '@akeneo_elasticsearch.client.product'
            - 'pim_catalog_product'

    pcmt_core.service.e2Open.trade_item_xml_processor:
        class: PcmtCoreBundle\Service\E2Open\TradeItemXmlProcessor
        arguments:
            - '@monolog.logger'
            - '@pcmt_e2Open_attributes_service'
            - '@pim_catalog.updater.product'