######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt_create_attribute_manager:
        class: 'PcmtCoreBundle\Extension\PcmtAttributeManager'
        autowire: true

    #util command for the one below (PcmtCreateAllAttributesCommand)
    PcmtCoreBundle\Command\PcmtCreateAttributeForRefDataCommand:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:generate-ref-data-attr' }

    #util command - generate default reference data simple select attributes
    PcmtCoreBundle\Command\PcmtCreateAllAttributesCommand:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:generate-ref-data-attr-all' }

    PcmtCoreBundle\Command\Creator\PcmtJobCreator:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:job-creator' }

    PcmtCoreBundle\Command\InitializeReferenceDataImport:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:reference_data:create' }

    pcmt_e2Open_mapping:
        class: PcmtCoreBundle\Connector\Mapping\E2OpenMapping
        autowire: true

    pcmt_e2Open_mapping_handler:
        class: PcmtCoreBundle\Service\Handler\E2OpenMappingHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.repository.family'
            - '@pcmt_catalog.repository.e2open_attribute_mapping'