######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt_connector.step.pcmt_e2open.export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product'
            - '@pim_connector.processor.normalization.product'
            - '@pcmt_connector.writer.file.e2open'
            - '%pim_job_product_batch_size%'
            -
    pcmt_connector.step.pcmt_e2open.import:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - 'pcmt_e2open_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pcmt_connector.tasklet.pcmt_e2open_import'

    pcmt_connector.step.pcmt_mst_supplier.export:
        class: 'PcmtCoreBundle\Connector\Job\Step\MstSupplierExportStep'
        arguments:
            - 'export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pcmt_connector.reader.database.mst_supplier_export'
            - '@pim_connector.processor.normalization.product'
            - '@pcmt_connector.writer.file.mst_supplier'
            - '%pim_job_product_batch_size%'

    pcmt_connector.step.hash_first_cell:
        class: 'PcmtCoreBundle\Connector\Job\Step\HashFirstCellStep'
        arguments:
            - 'hash_first_cell'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'

    pcmt_xml_connector.step.xml_reference_data_download:
        class: PcmtCoreBundle\Step\ImportRefDataFiles
        arguments:
            - 'import_xml_data_files'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'

    pcmt_xml_connector.step.xml_reference_data_import:     #one instance of a job will be responsible to parse one file, shell/python script will be instantiating jobs for several files
        class: Akeneo\Tool\Component\Batch\Step\ItemStep          # and passing serialized filename as a parameter for each job
        arguments:
            - 'process'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pcmt_connector.reader.xml.reference_data_gs1'
            - '@pcmt_connector.processor.reference_data'
            - '@pcmt_connector.write.reference_data'