######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt_catalog.product.updater.concatenated_attributes_for_product_and_model:
        class: PcmtCoreBundle\Updater\ConcatenatedAttributesUpdater
        arguments:
            - '@pim_catalog.updater.entity_with_values'
            - '@pim_storage_serializer'

    pcmt_catalog.draft.manager:
        class: PcmtCoreBundle\Manager\DraftManager

    pim_structure.updater.translatable:
        class: 'PcmtCoreBundle\Updater\TranslatableUpdater'

    pim_catalog.updater.family:
        class: 'PcmtCoreBundle\Updater\PcmtFamilyUpdater'
        arguments:
            - '@pim_catalog.repository.product'
            - '@event_dispatcher'
            - '@logger'
            - '@pim_catalog.repository.family'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.factory.attribute_requirement'
            - '@pim_catalog.repository.attribute_requirement'
            - '@pim_structure.updater.translatable'

    pim_catalog.updater.attribute:
        class: 'PcmtCoreBundle\Updater\AttributeUpdater'
        arguments:
            - '@pim_catalog.repository.attribute_group'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.registry.attribute_type'
            - '@pim_structure.updater.translatable'
            - '@pcmt_create_attribute_manager'
            - ['auto_option_sorting', 'is_read_only']

    ## field setters
    pcmt_catalog.updater.setter.concatenated_value:
        class: '%pim_catalog.updater.setter.value.class%'
        parent: pim_catalog.updater.setter.abstract
        arguments:
            - ['pcmt_catalog_concatenated']
        tags:
            - { name: 'pim_catalog.updater.setter' }