######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: '3.4'
services:
  pim:
    image: pcmt/pcmt
    build:
      context: .
      target: pim
  httpd:
    image: pcmt/httpd
    build:
      context: .
      target: httpd
