######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: '3.4'
services:
  pim:
    image: pcmt/pcmt:${PCMT_VER:-latest}
    build:
      context: .
      target: pim
  node:
    image: pcmt/node:${PCMT_VER:-latest}
    build:
      context: .
      target: node
  httpd:
    image: pcmt/httpd:${PCMT_VER:-latest}
    build:
      context: .
      target: httpd
