######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

pcmt_permission_cis_view:
    type: action
    label: pcmt.permission.cis.label.view
    group_name: pcmt.permission.cis

pcmt_permission_cis_create:
    type: action
    label: pcmt.permission.cis.label.create
    group_name: pcmt.permission.cis

pcmt_permission_cis_edit:
    type: action
    label: pcmt.permission.cis.label.edit
    group_name: pcmt.permission.cis

pcmt_permission_cis_delete:
    type: action
    label: pcmt.permission.cis.label.delete
    group_name: pcmt.permission.cis
