datagrid:
    gs1codes:
        options:
            entityHint: gs1code
            manageFilters: false
        source:
            type: pim_datasource_default
            entity: Pcmt\Bundle\Entity\ReferenceData\GS1Codes\GS1Code
            repository_method: createDataGridQueryBuilder
        columns:
            name:
                label: pcmt.gs1code.field.listName
