parameters:
    pim_connector.array_converter.standard_to_flat.attribute.class: 'Pcmt\PcmtAttributeBundle\ArrayConverter\StandardToFlat\Attribute'
    pim_connector.array_converter.flat_to_standard.attribute.class: 'Pcmt\PcmtAttributeBundle\ArrayConverter\FlatToStandard\Attribute'

services:
    pim_connector.array_converter.standard_to_flat.attribute:
        class: 'Pcmt\PcmtAttributeBundle\ArrayConverter\StandardToFlat\Attribute'
        arguments:
            -
                - 'localizable'
                - 'useable_as_grid_filter'
                - 'unique'
                - 'required'
                - 'scopable'
                - 'wysiwyg_enabled'
                - 'decimals_allowed'
                - 'negative_allowed'
                - 'auto_option_sorting'
                - 'is_read_only'

    pim_connector.array_converter.flat_to_standard.attribute:
        class: 'Pcmt\PcmtAttributeBundle\ArrayConverter\FlatToStandard\Attribute'
        arguments:
            - '@pim_connector.array_convertor.checker.fields_requirement'
            -
                - 'localizable'
                - 'useable_as_grid_filter'
                - 'unique'
                - 'required'
                - 'scopable'
                - 'wysiwyg_enabled'
                - 'decimals_allowed'
                - 'negative_allowed'
                - 'auto_option_sorting'
                - 'is_read_only'

    pim_connector.array_converter.flat_to_standard.concatenated_attribute:
        class: 'Pcmt\PcmtAttributeBundle\Extension\Connector\ArrayConverter\StandardToFlat\Product\ConcatenatedAttributesConverter'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
            - ['pcmt_catalog_concatenated']
        tags:
            - { name: 'pim_connector.array_converter.standard_to_flat.product.value_converter' }