services:

    ### Concatenated fields for attribute
    pcmt_catalog.normalizer.standard.concatenated_attribute:
        class: 'Pcmt\PcmtAttributeBundle\Normalizer\Standard\ConcatenatedTypeNormalizer'
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }

    ### Attribute
    pim_catalog.normalizer.standard.attribute:
        class: 'Pcmt\PcmtAttributeBundle\Normalizer\Standard\AttributeNormalizer'
        arguments:
            - '@pcmt_catalog.normalizer.standard.concatenated_attribute'
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.normalizer.standard.datetime'
            - ['auto_option_sorting']
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }
