extensions:
  pcmt-rules-index:
    module: pim/common/simple-view
    targetZone: self
    config:
      template: pim/template/common/default-template

  pcmt-rules-index-grid-container:
    module: pim/common/simple-view
    parent: pcmt-rules-index
    targetZone: content
    config:
      template: pim/template/form/index/index

  pcmt-rules-index-user-navigation:
    module: pim/menu/user-navigation
    parent: pcmt-rules-index
    targetZone: user-menu
    config:
      userAccount: pim_menu.user.user_account
      logout: pim_menu.user.logout

  pcmt-rules-index-grid-title:
    module: pim/common/grid-title
    parent: pcmt-rules-index
    targetZone: title
    config:
      title: pim_enrich.entity.rules.page_title.index

  pcmt-rules-index-breadcrumbs:
    module: pim/common/breadcrumbs
    parent: pcmt-rules-index
    targetZone: breadcrumbs
    config:
      tab: pim-menu-system
      item: pim-menu-system-rules