extensions:
  pim-menu-system-cis:
    module: pim/menu/item
    parent: pim-menu-system-navigation-block
    aclResourceId: pcmt_permission_cis_view
    position: 130
    config:
      title: pim_menu.item.cis
      to: pcmt_cis_index
