extensions:
  pcmt-rules-create-modal:
    module: pcmt/rules/form/common/creation/modal
    config:
      labels:
        title: pim_common.create
        subTitle: pim_menu.item.rules
      picture: illustrations/Family.svg
      successMessage: pcmt.entity.rules.flash.create.success
      editRoute: pcmt_rules_edit
      postUrl: pcmt_rule_rest_create
      routerKey: id

  pcmt-rules-create-code:
    module: pim/form/common/fields/text
    parent: pcmt-rules-create-modal
    position: 10
    targetZone: fields
    config:
      fieldName: unique_id
      required: true
      label: pcmt.rules.create.unique_id

  pcmt-rules-create-family-a:
    module: pcmt/rules/form/properties/family
    parent: pcmt-rules-create-modal
    targetZone: fields
    position: 20
    config:
      fieldName: source_family
      required: true
      label: pcmt.rules.create.source_family

  pcmt-rules-create-family-b:
    module: pcmt/rules/form/properties/family
    parent: pcmt-rules-create-modal
    targetZone: fields
    position: 22
    config:
      fieldName: destination_family
      required: true
      label: pcmt.rules.create.destination_family

  pcmt-rules-create-key-attribute:
    module: pcmt/rules/form/properties/key-attribute
    parent: pcmt-rules-create-modal
    targetZone: fields
    position: 25
    config:
      fieldName: key_attribute
      required: true
      label: pcmt.rules.create.key_attribute
      tooltip: pcmt.rules.info.key_attribute

