extensions:
  pcmt-rules-create-modal:
    module: pcmt/form/common/creation/modal
    config:
      labels:
        title: pim_common.create
        subTitle: pim_menu.item.rules
      picture: illustrations/Family.svg
      successMessage: pcmt.entity.rules.flash.create.success
      editRoute: pcmt_rules_index
      postUrl: pcmt_rule_rest_create
      routerKey: unique_id

  pcmt-rules-create-code:
    module: pim/form/common/fields/text
    parent: pcmt-rules-create-modal
    position: 10
    targetZone: fields
    config:
      fieldName: unique_id
      required: true
      label: pcmt.rules.create.unique_id

  pcmt-rules-create-family-a:
    module: pcmt/form/propeties/family
    parent: pcmt-rules-create-modal
    targetZone: fields
    position: 20
    config:
      fieldName: source_family
      required: true
      label: pcmt.rules.create.source_family

  pcmt-rules-create-family-b:
    module: pcmt/form/propeties/family
    parent: pcmt-rules-create-modal
    targetZone: fields
    position: 20
    config:
      fieldName: destination_family
      required: true
      label: pcmt.rules.create.destination_family
