extensions:
  pcmt-rules-edit-form:
    module: pim/form/common/edit-form
    aclResourceId: pcmt_permission_rules_edit

  pcmt-rules-edit-form-breadcrumbs:
    module: pim/common/breadcrumbs
    parent: pcmt-rules-edit-form
    targetZone: breadcrumbs
    config:
      tab: pim-menu-system
      item: pim-menu-system-rules

  pcmt-rules-edit-form-user-navigation:
    module: pim/menu/user-navigation
    parent: pcmt-rules-edit-form
    targetZone: user-menu
    config:
      userAccount: pim_menu.user.user_account
      logout: pim_menu.user.logout

  pcmt-rules-edit-form-label:
    module: pim/form/common/label
    parent: pcmt-rules-edit-form
    targetZone: title
    position: 90

  pcmt-rules-edit-form-secondary-actions:
    module: pim/form/common/secondary-actions
    parent: pcmt-rules-edit-form
    targetZone: buttons
    position: 50

  pcmt-rules-edit-form-save-buttons:
    module: pim/form/common/save-buttons
    parent: pcmt-rules-edit-form
    targetZone: buttons
    position: 110

  pcmt-rules-edit-form-save:
    module: pcmt/rules/form/common/save-rule-form
    parent: pcmt-rules-edit-form
    targetZone: buttons
    position: 0
    config:
      updateSuccessMessage: pcmt.entity.rules.flash.update.success
      updateFailureMessage: pcmt.entity.rules.flash.update.fail
      notReadyMessage: pim_enrich.entity.rules.flash.update.fields_not_ready
      url: pcmt_rule_rest_edit
      identifierParamName: id
      entityIdentifierParamName: id
      redirectAfter: pcmt_rules_edit
      redirectAfterRouteIdentifierParamName: id
      excludedProperties: []

  pcmt-rules-edit-form-state:
    module: pim/form/common/state
    parent: pcmt-rules-edit-form
    targetZone: state
    position: 900
    config:
      entity: pcmt.entity.rules.label

  pcmt-rules-edit-form-form-tabs:
    module: pim/form/common/form-tabs
    parent: pcmt-rules-edit-form
    targetZone: content
    position: 100

  pcmt-rules-edit-form-properties-tab:
    module: pim/common/tab
    parent: pcmt-rules-edit-form-form-tabs
    targetZone: container
    position: 100
    config:
      label: pim_common.properties

  pcmt-rules-edit-form-properties:
    module: pim/common/simple-view
    parent: pcmt-rules-edit-form-properties-tab
    targetZone: self
    config:
      template: pim/template/form/tab/sections

  pcmt-rules-edit-form-properties-common:
    module: pim/common/simple-view
    parent: pcmt-rules-edit-form-properties
    targetZone: accordion
    position: 100
    config:
      template: pim/template/form/tab/section
      templateParams:
        sectionTitle: pcmt.entity.rules.module.edit.common
        dropZone: content

  pcmt-rules-edit-form-properties-common-unique-id:
    module: pim/form/common/fields/text
    parent: pcmt-rules-edit-form-properties-common
    targetZone: content
    position: 90
    config:
      fieldName: unique_id
      label: pcmt.rules.edit.unique_id
      required: true

  pcmt-rules-edit-form-properties-common-source-family:
    module: pcmt/rules/form/properties/family
    parent: pcmt-rules-edit-form-properties-common
    targetZone: content
    position: 100
    config:
      fieldName: source_family
      label: pcmt.rules.edit.source_family
      required: true

  pcmt-rules-edit-form-properties-common-destination-family:
    module: pcmt/rules/form/properties/family
    parent: pcmt-rules-edit-form-properties-common
    targetZone: content
    position: 110
    config:
      fieldName: destination_family
      label: pcmt.rules.edit.destination_family
      required: true

  pcmt-rules-edit-form-properties-common-key-attribute:
    module: pcmt/rules/form/properties/key-attribute
    parent: pcmt-rules-edit-form-properties-common
    targetZone: content
    position: 120
    config:
      fieldName: key_attribute
      label: pcmt.rules.edit.key_attribute
      tooltip: pcmt.rules.info.key_attribute
      required: true