Pcmt\PcmtProductBundle\Entity\Attribute:
    type: entity
    table: pim_catalog_attribute
    changeTrackingPolicy: DEFERRED_EXPLICIT
    indexes:
        searchcode_idx:
            columns:
                - code
    repositoryClass: Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\AttributeRepository
    uniqueConstraints:
        searchunique_idx:
            columns:
                - code
                - entity_type