Pcmt\PcmtProductBundle\Entity\ProductDraftHistory:
    type: entity
    table: pcmt_catalog_product_draft_history
    changeTrackingPolicy: DEFERRED_EXPLICIT
    repositoryClass: Pcmt\PcmtProductBundle\Entity\DraftHistoryRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        changeSet:
            type: native_json
            column: change_set
        createdAt:
             type: datetime
    manyToOne:
        author:
            targetEntity: Akeneo\UserManagement\Component\Model\UserInterface
            joinColumns:
                author:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        draft:
            targetEntity: Pcmt\PcmtProductBundle\Entity\ProductAbstractDraft
            inversedBy: draftHistoryEntries
            joinColumns:
                draft_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'