######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

extensions:
  pim-product-model-edit-form-attribute-description:
    module: dnd/product-edit-form/attributes/description
    parent: pim-product-model-edit-form-attributes
    targetZone: self
    position: 100
