imports:
  - { resource: steps.yml }
  - { resource: jobs.yml }

services:

  Pcmt\PcmtConnectorBundle\Command\Creator\PcmtJobCreator:
    autowire: true
    tags:
      - { name: 'console.command', command: 'pcmt:job-creator' }

  Pcmt\PcmtConnectorBundle\Command\InitializeReferenceDataImport:
    autowire: true
    tags:
      - { name: 'console.command', command: 'pcmt:reference_data:create' }