services:

  pcmt_connector.job.pcmt_xlsx_product_import:
    class: '%pim_connector.job.simple_job.class%'
    arguments:
      - 'pcmt_xlsx_product_import'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      -
        - '@pim_connector.step.charset_validator'
        - '@pcmt_connector.step.pcmt_xlsx_product.import'
        - '@pim_connector.step.xlsx_product.import_associations'
    tags:
      - { name: akeneo_batch.job, connector: 'Pcmt Connector', type: '%pim_connector.job.import_type%' }