parameters:
  pcmt_connector.updater.datagrid_view.class: Pcmt\PcmtCustomDatasetBundle\Updater\PcmtDatagridViewUpdater

services:
  pcmt_connector.updater.datagrid_view:
    class: '%pcmt_connector.updater.datagrid_view.class%'
    arguments:
      - '@pim_user.repository.user'
