######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

PcmtRulesBundle\Entity\Rule:
    type: entity
    table: pcmt_rule
    repositoryClass: PcmtRulesBundle\Repository\RuleRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        uniqueId:
            type: string
            unique: true
            column: unique_id
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ updateTimestamps ]
        preUpdate: [ updateTimestamps ]
    manyToOne:
        sourceFamily:
            targetEntity: Akeneo\Pim\Structure\Component\Model\Family
            joinColumns:
                source_family_id:
                    nullable: true
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        destinationFamily:
            targetEntity: Akeneo\Pim\Structure\Component\Model\Family
            joinColumns:
                destination_family_id:
                    nullable: true
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        keyAttribute:
            targetEntity: Akeneo\Pim\Structure\Component\Model\AttributeInterface
            joinColumns:
                key_attribute_id:
                    nullable: true
                    referencedColumnName: id
                    onDelete: 'SET NULL'
