pcmt_rule_rest_get:
    path: /{id}
    defaults: { _controller: pcmt.controller.rest.rules:getAction }
    methods: [GET]

pcmt_rule_rest_create:
    path: /
    defaults: { _controller: pcmt.controller.rest.rules:createAction }
    methods: [PUT]

pcmt_rule_rest_edit:
    path: /{id}
    defaults: { _controller: pcmt.controller.rest.rules:postAction }
    requirements:
        id: '[0-9_]+'
    methods: [POST]

pcmt_rule_rest_run:
    path: /{id}/run
    defaults: { _controller: pcmt.controller.rest.rules:runAction }
    requirements:
        id: \d+