services:
    pcmt.datasource.rule:
        class: '%pim_datagrid.datasource.repository.class%'
        arguments:
            - '@pcmt.repository.rule'
            - '@pim_datagrid.datasource.result_record.hydrator.default'
        tags:
            - { name: oro_datagrid.datasource, type: pcmt_datasource_rule }