config:
  paths:
    pcmt/rules/index: pcmtrules/js/controller/rule_index
    pcmt/rules/edit: pcmtrules/js/controller/rule_edit
    pcmt/rules/fetcher: pcmtrules/js/fetcher/rule_fetcher
    pcmt/rules/fetcher/key-attribute-for-rules: pcmtrules/js/fetcher/key-attribute-for-rules-fetcher

    pcmt/rules/form/common/creation/modal: pcmtrules/js/form/common/creation/modal
    pcmt/rules/form/common/save-rule-form: pcmtrules/js/form/common/save-rule-form

    pcmt/rules/form/properties/family: pcmtrules/js/form/properties/family
    pcmt/rules/form/properties/key-attribute: pcmtrules/js/form/properties/key-attribute

    pcmt/rules/template/group: pcmtrules/templates/group.html

  config:
    pim/controller-registry:
      controllers:
        pcmt_rules_index:
          module: pcmt/rules/index
        pcmt_rules_edit:
          module: pcmt/rules/edit
    pim/fetcher-registry:
      fetchers:
        default: pim/base-fetcher
        rule:
          module: pcmt/rules/fetcher
          options:
            urls:
              get: pcmt_rule_rest_get
        key-attribute-for-rule:
          module: pcmt/rules/fetcher/key-attribute-for-rules
          options:
            identifier_type: pim_catalog_identifier
            urls:
              list: pcmt_rules_attributes_for_families
              get: pim_enrich_attribute_rest_get