config:
  paths:
    pcmt/rules/index: pcmtrules/js/controller/rule_index

    pcmt/form/common/creation/modal:                      pcmtrules/js/form/common/creation/modal
  config:
    pim/controller-registry:
      controllers:
        pcmt_rules_index:
          module: pcmt/rules/index