######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################
parameters:
    pcmt.entity.rule.class:  PcmtRulesBundle\Entity\Rule
    pim_datagrid.event_listener.add_username_to_grid_listener.class: PcmtRulesBundle\Listener\AddUsernameToGridListener

services:

    pcmt.rule.normalizer:
        class: PcmtRulesBundle\Normalizer\RuleNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 80 }

    pcmt.repository.rule:
        class: PcmtRulesBundle\Repository\RuleRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pcmt.entity.rule.class%']
        tags:
            - { name: 'pim_repository' }