services:

    pcmt.updater.rule:
        class: 'PcmtRulesBundle\Updater\RuleUpdater'
        arguments:
            - '@pim_catalog.repository.family'
            - '@pim_catalog.repository.attribute'