######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt_permissions.normalizer.internal.attribute_groups:
        class: 'PcmtPermissionsBundle\Normalizer\AttributeGroupNormalizer'
        arguments:
            - '@pim_enrich.normalizer.attribute_group'
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 200 }
