######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################
parameters:

services:
    pcmt_permissions.repository.category_access:
        class: PcmtPermissionsBundle\Repository\CategoryAccessRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['PcmtPermissionsBundle\Entity\CategoryAccess']
        tags:
            - { name: 'pcmt_repository' }

    pcmt_permissions.saver.category_access:
        class: PcmtPermissionsBundle\Saver\CategoryAccessSaver
        arguments:
            - '@doctrine.orm.entity_manager'
