######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################
parameters:
    pim_enrich.view_element.category.tab.property.template: 'PcmtPermissionsBundle:CategoryTree:Tab/property.html.twig'

services:
    pcmt_permissions.repository.category_access:
        class: PcmtPermissionsBundle\Repository\CategoryAccessRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['PcmtPermissionsBundle\Entity\CategoryAccess']
        tags:
            - { name: 'pcmt_repository' }

    pcmt_permissions.saver.category_access:
        class: PcmtPermissionsBundle\Saver\CategoryAccessSaver
        arguments:
            - '@doctrine.orm.entity_manager'

    pcmt_permissions.saver.category_with_access:
        class: PcmtPermissionsBundle\Saver\CategoryWithAccessSaver
        arguments:
            - '@pim_catalog.saver.category'
            - '@pcmt_permissions.saver.category_access'
            - '@doctrine.orm.entity_manager'
            - '@pcmt_permissions.repository.category_access'

    pcmt_permissions.form.category:
        class: 'PcmtPermissionsBundle\Form\CategoryType'
        arguments:
            - 'PcmtPermissionsBundle\Entity\CategoryWithAccess'
            - '%pim_catalog.entity.category_translation.class%'
        tags:
            - { name: form.type, alias: pim_category }

    pim_enrich.doctrine.counter.category_product:
        class: 'PcmtPermissionsBundle\Counter\CategoryProductsCounter'
        arguments:
            - '@pim_catalog.query.product_query_builder_factory'
            - '@pim_catalog.repository.category'
        tags:
            - { name: pim_enrich.doctrine.counter.category_item, type: product }

    pcmt_permissions.updater.category_children_permissions:
        class: PcmtPermissionsBundle\Updater\CategoryChildrenPermissionsUpdater
        arguments:
            - '@pcmt_permissions.repository.category_access'
            - '@pcmt_permissions.saver.category_with_access'

    pcmt.service.checker.category_permissions_checker:
        class: PcmtPermissionsBundle\Service\Checker\CategoryPermissionsChecker
        autowire: true

    PcmtPermissionsBundle\Validator\Constraints\UniqueEntityValidator:
        class: PcmtPermissionsBundle\Validator\Constraints\UniqueEntityValidator
        autowire: true
        tags:
            - { name: validator.constraint_validator, alias: pcmt_permissions_unique_entity_validator }