PcmtCoreBundle\Entity\Mapping\AttributeMapping:
  type: entity
  table: pcmt_catalog_attribute_mapping
  changeTrackingPolicy: DEFERRED_EXPLICIT
  repositoryClass: PcmtCoreBundle\Repository\AttributeMappingRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  OneToOne:
    E2OpenAttribute:
      targetEntity: Attribute
      joinColumn:
        name: e2open_attribute_id
        referencedColumnName: id
    mappedAttribute:
      targetEntity: Attribute
      joinColumn:
        name: mapped_attribute_id
        referencedColumnName: id
