services:
    pcmt_product.controller.rest.draft:
        class: Pcmt\PcmtProductBundle\Controller\PcmtProductDraftController
        autowire: true
        arguments:
            $constraintViolationNormalizer: '@pim_enrich.normalizer.product_violation'
    ### overrides product controller
    pim_enrich.controller.rest.product:
        class: Pcmt\PcmtProductBundle\Controller\PcmtProductController
        arguments:
            - '@event_dispatcher'
            - '@pim_versioning.repository.version'
            - '@pcmt_product.save.productDraft'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.updater.product'
            - '@pim_catalog.saver.product'
            - '@pim_internal_api_serializer'
            - '@pim_catalog.validator.product'
            - '@pim_user.context.user'
            - '@pim_catalog.filter.chained'
            - '@pim_enrich.filter.product_edit_data'
            - '@pim_catalog.remover.product'
            - '@pim_catalog.builder.product'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_catalog.comparator.filter.product'
            - '@pim_enrich.converter.enrich_to_standard.product_value'
            - '@pim_enrich.normalizer.product_violation'
            - '@pim_catalog.builder.product'
            - '@pim_enrich.filter.product_attribute_filter'
            - '@akeneo_elasticsearch.client.product'
            - '@akeneo_elasticsearch.client.product_and_product_model'
