parameters:
    pim_catalog.entity.attribute_translation.class: Pcmt\PcmtProductBundle\Entity\AttributeTranslation

    pim_catalog.entity.attribute.class: Pcmt\PcmtProductBundle\Entity\Attribute
    pim_catalog.repository.concatenated_attribute.class: Pcmt\PcmtProductBundle\Entity\PcmtFamilyRepository

services:

    pcmt_catalog.repository.pcmt_family_concatenated_attribute:
        class: '%pim_catalog.repository.concatenated_attribute.class%'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.family.class%']
        tags:
            - { name: 'pim_repository' }

