services:

    pcmt_enrichment.provider.form.product_job_instance:
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
        arguments:
            -   pcmt_e2open_export: pim-job-instance-xlsx-base-export
        tags:
            - { name: pim_enrich.provider.form, priority: 100 }