services:
    pcmt_catalog.job.job_parameters.default_values_provider.compute_family_products_concatenated_attributes_values:
        class: '%akeneo_batch.job.job_parameters.empty_values_provider.class%'
        arguments:
            -  [ '%pcmt_catalog.compute_family_products_concatenated_attributes_values.job_name%' ]
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }