services:
    pcmt_connector.job.pcmt_e2open_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'pcmt_e2open_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pcmt_connector.step.pcmt_e2open.export'
                - '@pcmt_connector.step.hash_first_cell'
        tags:
            - { name: akeneo_batch.job, connector: 'Pcmt Connector', type: '%pim_connector.job.export_type%' }
