services:
    pcmt_catalog.draft_new.property_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\NewDraftPropertyNormalizer
        autowire: true
    pcmt_catalog.draft_pending.property_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\PendingDraftPropertyNormalizer
    pcmt_product.draft.status.normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\DraftStatusNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 80 }
    pcmt_product.draft.attribute_change.normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\AttributeChangeNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 120 }
    pcmt_product.draft.product_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\ProductDraftNormalizer
        autowire: true
        calls:
            - [setProductFromDraftCreator, ['@pcmt.service.product_from_draft_creator']]
            - [setProductAttributeChangeService, ['@pcmt.service.product_attribute_change']]
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 110 }
    pcmt_product.draft.product_model_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\ProductModelDraftNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 110 }
        calls:
            - [setProductModelFromDraftCreator, ['@pcmt.service.product_model_from_draft_creator']]
            - [setProductModelAttributeChangeService, ['@pcmt.service.product_model_attribute_change']]

    ### Concatenated fields for attribute
    pcmt_catalog.normalizer.standard.concatenated_attribute:
        class: 'Pcmt\PcmtProductBundle\Normalizer\Standard\ConcatenatedTypeNormalizer'
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }

    ### Attribute
    pim_catalog.normalizer.standard.attribute:
        class: 'Pcmt\PcmtProductBundle\Normalizer\Standard\AttributeNormalizer'
        arguments:
            - '@pcmt_catalog.normalizer.standard.concatenated_attribute'
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.normalizer.standard.datetime'
            - ['auto_option_sorting']
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }

parameters:
    pim_catalog.normalizer.standard.translation.class: Pcmt\PcmtProductBundle\Normalizer\Standard\TranslationNormalizer




