services:
    pcmt_catalog.draft_new.property_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\NewDraftPropertyNormalizer
        autowire: true
    pcmt_catalog.draft_pending.property_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\PendingDraftPropertyNormalizer
    pcmt_product.draft.status.normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\DraftStatusNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 80 }
    pcmt_product.draft.attribute_change.normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\AttributeChangeNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 120 }
    pcmt_product.draft.product_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\ProductDraftNormalizer
        autowire: true
        calls:
            - [setProductFromDraftCreator, ['@pcmt.service.product_from_draft_creator']]
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 110 }
    pcmt_product.draft.product_model_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\ProductModelDraftNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 110 }



