services:

    pcmt_catalog.draft_new.property_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\NewDraftPropertyNormalizer
        autowire: true

    pcmt_catalog.draft_pending.property_normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\PendingDraftPropertyNormalizer

    pcmt_product.draft.normalizer:
        class: Pcmt\PcmtProductBundle\Normalizer\DraftNormalizer
        arguments:
            - '@serializer.normalizer.object'
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 110 }

