services:
    pcmt_connector.job.job_parameters.default_values_provider.pcmt_simple_xlsx_product_export:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleXlsxExport'
        arguments:
            -
                - 'pcmt_e2open_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }


    pcmt_connector.job.job_parameters.constraint_collection_provider.pcmt_simple_xlsx_product_export:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleXlsxExport'
        arguments:
            -
                - 'pcmt_e2open_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
