pcmt_product_drafts_index:
    path: /drafts/
pcmt_product_drafts_edit:
    path: /drafts/edit/{id}/
pcmt_product_drafts_api:
    path: /rest/drafts/
    defaults: { _controller: pcmt_product.controller.rest.draft:getList }
    methods: [GET]
pcmt_product_draft_api:
    path: /rest/drafts/{id}/
    defaults: { _controller: pcmt_product.controller.rest.draft:getDraft }
    requirements:
        id: \d+
    methods: [GET]
pcmt_product_drafts_params:
    path: /rest/drafts/params/
    defaults: { _controller: pcmt_product.controller.rest.draft:getListParams }
    methods: [GET]
pcmt_product_drafts_delete:
    path: /rest/draft/{id}/
    defaults: { _controller: pcmt_product.controller.rest.draft:rejectDraft }
    requirements:
        id: \d+
    methods: [DELETE]
pcmt_product_drafts_approve_bulk:
    path: /rest/draft/approval/bulk/
    defaults: { _controller: pcmt_product.controller.rest.draft:approveBulkDraft }
    methods: [PUT]
pcmt_product_drafts_approve:
    path: /rest/draft/approval/{id}/
    defaults: { _controller: pcmt_product.controller.rest.draft:approveDraft }
    requirements:
        id: \d+
    methods: [PUT]
