services:
    pcmt.controller.product_draft:
        class: Pcmt\PcmtProductBundle\Controller\PcmtProductDraftController
        calls:
            - [ setSecurityFacade, ['@oro_security.security_facade'] ]
