services:
    pcmt.manager.draft_facade:
        class: Pcmt\PcmtProductBundle\Manager\DraftFacade
        autowire: true
    pcmt.service.product_draft_approver:
        class: Pcmt\PcmtProductBundle\Service\DraftApprover
        autowire: true
        arguments:
            $productValidator: '@pim_catalog.validator.product'
            $productSaver: '@pim_catalog.saver.product'
    pcmt.service.product_from_draft_creator:
        class: Pcmt\PcmtProductBundle\Service\ProductFromDraftCreator
        arguments:
            - '@pim_catalog.builder.product'
            - '@pim_enrich.converter.enrich_to_standard.product_value'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_user.context.user'
            - '@pim_catalog.comparator.filter.product'
            - '@pim_catalog.updater.product'
            - '@pim_enrich.filter.product_attribute_filter'
