services:

    pcmt_catalog.product.updater.concatenated_attributes_for_product_and_model:
        class: Pcmt\PcmtProductBundle\Updater\ConcatenatedAttributesUpdater
        arguments:
            - '@pim_catalog.updater.entity_with_values'
            - '@pim_storage_serializer'

    pcmt_catalog.draft.manager:
        class: Pcmt\PcmtProductBundle\Manager\DraftManager

    pim_structure.updater.translatable:
        class: 'Pcmt\PcmtProductBundle\Updater\TranslatableUpdater'

    pim_catalog.updater.family:
        class: 'Pcmt\PcmtProductBundle\Updater\PcmtFamilyUpdater'
        arguments:
            - '@pim_catalog.repository.product'
            - '@event_dispatcher'
            - '@logger'
            - '@pim_catalog.repository.family'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.factory.attribute_requirement'
            - '@pim_catalog.repository.attribute_requirement'
            - '@pim_structure.updater.translatable'