services:
    pcmt_connector.writer.file.e2open:
        class: 'Pcmt\PcmtProductBundle\Connector\Job\Writer\E2OpenWriter'
        arguments:
            - '@pim_connector.array_converter.standard_to_flat.product_localized'
            - '@pim_connector.factory.flat_item_buffer'
            - '@pim_connector.writer.file.product.flat_item_buffer_flusher'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.writer.file.media_exporter_path_generator'
            - '@akeneo.pim.enrichment.connector.write.file.flat.generate_headers_from_family_codes'
            - '@akeneo.pim.enrichment.connector.write.file.flat.generate_headers_from_attribute_codes'
            - ['pim_catalog_file', 'pim_catalog_image']