extensions:
  pcmt-cis-create-modal:
    module: pim/form/common/creation/modal
    config:
      labels:
        title: pim_common.create
        subTitle: pim_menu.item.cis
      picture: illustrations/Family.svg
      successMessage: pcmt.entity.cis.flash.create.success
      editRoute: pcmt_cis_index
      postUrl: pcmt_cis_rest_create
      routerKey: id

  pcmt-cis-create-data-recipient-gln:
    module: pim/form/common/fields/number
    parent: pcmt-cis-create-modal
    targetZone: fields
    position: 20
    config:
      fieldName: data_recipient_gln
      label: pcmt.cis.create.data_recipient_gln

  pcmt-cis-create-data-source-gln:
    module: pim/form/common/fields/number
    parent: pcmt-cis-create-modal
    targetZone: fields
    position: 20
    config:
      fieldName: data_source_gln
      label: pcmt.cis.create.data_source_gln

  pcmt-cis-create-gtin:
    module: pim/form/common/fields/number
    parent: pcmt-cis-create-modal
    targetZone: fields
    position: 20
    config:
      fieldName: gtin
      label: pcmt.cis.create.gtin

  pcmt-cis-create-gpc-category-code:
    module: pim/form/common/fields/text
    parent: pcmt-cis-create-modal
    targetZone: fields
    position: 20
    config:
      fieldName: gpc_category_code
      label: pcmt.cis.create.gpc_category_code

  pcmt-cis-create-target-market-country-code:
    module: pcmt/cis/form/properties/country_codes
    parent: pcmt-cis-create-modal
    targetZone: fields
    position: 20
    config:
      fieldName: target_market_country_code
      label: pcmt.cis.create.target_market_country_code
