extensions:
  pcmt-cis-index:
    module: pim/common/simple-view
    targetZone: self
    config:
      template: pim/template/common/default-template

  pcmt-cis-index-grid-container:
    module: pim/common/simple-view
    parent: pcmt-cis-index
    targetZone: content
    config:
      template: pim/template/form/index/index

  pcmt-cis-index-user-navigation:
    module: pim/menu/user-navigation
    parent: pcmt-cis-index
    targetZone: user-menu
    config:
      userAccount: pim_menu.user.user_account
      logout: pim_menu.user.logout

  pcmt-cis-index-grid-title:
    module: pim/common/grid-title
    parent: pcmt-cis-index
    targetZone: title
    config:
      title: pim_enrich.entity.cis.page_title.index

  pcmt-cis-index-breadcrumbs:
    module: pim/common/breadcrumbs
    parent: pcmt-cis-index
    targetZone: breadcrumbs
    config:
      tab: pim-menu-system
      item: pim-menu-system-cis

  pcmt-cis-index-create-button:
    module: pim/form/common/index/create-button
    parent: pcmt-cis-index
    targetZone: buttons
    position: 100
    aclResourceId: pcmt_permission_cis_create
    config:
      iconName:  plus
      title:     pcmt.entity.cis.module.create.button
      modalForm: pcmt-cis-create-modal

